-- Analysis worksheet for Snowsight

USE DATABASE PDM;
USE SCHEMA PUBLIC;

-- 1. Engine life per fleet
SELECT
    m.FLEET,
    m.FAULT_MODES,
    COUNT(*)                          AS FAILURES_RECORDED,
    MIN(h.EVENT_CYCLE)                AS SHORTEST_LIFE_CYCLES,
    ROUND(AVG(h.EVENT_CYCLE), 1)      AS AVG_LIFE_CYCLES,
    MAX(h.EVENT_CYCLE)                AS LONGEST_LIFE_CYCLES
FROM MAINTENANCE_HISTORY h
JOIN MACHINE_DATA m ON m.MACHINE_ID = h.MACHINE_ID
GROUP BY m.FLEET, m.FAULT_MODES
ORDER BY AVG_LIFE_CYCLES;


-- 2. Lifetime OEE by fleet (2.0 h per cycle, 18 h unplanned repair)
WITH scored AS (
    SELECT
        m.FLEET,
        (p.CYCLES_FLOWN * 2.0)
            / (p.CYCLES_FLOWN * 2.0 + CASE WHEN p.FAILURE_FLAG THEN 18 ELSE 0 END) AS AVAILABILITY,
        LEAST(GREATEST(p.AVG_HEALTH_INDEX, 0), 1)                               AS PERFORMANCE,
        p.IN_SPEC_CYCLES / p.CYCLES_FLOWN                                        AS QUALITY
    FROM OPERATING_PERIODS p
    JOIN MACHINE_DATA m ON m.MACHINE_ID = p.MACHINE_ID
)
SELECT
    FLEET,
    ROUND(AVG(AVAILABILITY), 3)                          AS AVG_AVAILABILITY,
    ROUND(AVG(PERFORMANCE), 3)                           AS AVG_PERFORMANCE,
    ROUND(AVG(QUALITY), 3)                               AS AVG_QUALITY,
    ROUND(AVG(AVAILABILITY * PERFORMANCE * QUALITY), 3)  AS AVG_OEE
FROM scored
GROUP BY FLEET
ORDER BY AVG_OEE;


-- 3. In-service engines drifting fastest on SENSOR_11 (Ps30), last 15 cycles
WITH recent AS (
    SELECT r.MACHINE_ID, r.TIME_CYCLE, r.SENSOR_11
    FROM RAW_SENSOR_DATA r
    JOIN MACHINE_DATA m ON m.MACHINE_ID = r.MACHINE_ID AND m.STATUS = 'IN_SERVICE'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY r.MACHINE_ID ORDER BY r.TIME_CYCLE DESC) <= 15
)
SELECT
    MACHINE_ID,
    (COUNT(*) * SUM(TIME_CYCLE * SENSOR_11) - SUM(TIME_CYCLE) * SUM(SENSOR_11))
        / NULLIF(COUNT(*) * SUM(TIME_CYCLE * TIME_CYCLE) - SUM(TIME_CYCLE) * SUM(TIME_CYCLE), 0)
        AS SENSOR_11_SLOPE
FROM recent
GROUP BY MACHINE_ID
ORDER BY ABS(SENSOR_11_SLOPE) DESC
LIMIT 10;
-- For FD002/FD004, compare within one operating regime


-- 4. In-service engines in the worst recent condition
WITH recent AS (
    SELECT p.*
    FROM OPERATING_PERIODS p
    JOIN MACHINE_DATA m ON m.MACHINE_ID = p.MACHINE_ID AND m.STATUS = 'IN_SERVICE'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY p.MACHINE_ID ORDER BY p.PERIOD_INDEX DESC) <= 3
)
SELECT
    MACHINE_ID,
    MAX(END_CYCLE)                                  AS CYCLES_FLOWN,
    ROUND(AVG(AVG_HEALTH_INDEX), 3)                 AS RECENT_HEALTH_INDEX,
    ROUND(SUM(IN_SPEC_CYCLES) / SUM(CYCLES_FLOWN), 3) AS RECENT_IN_SPEC_RATE
FROM recent
GROUP BY MACHINE_ID
ORDER BY RECENT_HEALTH_INDEX, RECENT_IN_SPEC_RATE
LIMIT 10;


-- 5. Action outcomes by action type
SELECT
    ACTION_TYPE,
    COUNT(*) AS TOTAL_ACTIONS,
    SUM(CASE WHEN FAILURE_OCCURRED_FLAG = FALSE THEN 1 ELSE 0 END) AS FAILURE_AVOIDED,
    SUM(CASE WHEN FAILURE_OCCURRED_FLAG = TRUE THEN 1 ELSE 0 END)  AS FAILURE_OCCURRED_ANYWAY,
    SUM(CASE WHEN FAILURE_OCCURRED_FLAG IS NULL THEN 1 ELSE 0 END) AS OUTCOME_PENDING
FROM ACTION_OUTCOMES
GROUP BY ACTION_TYPE
ORDER BY TOTAL_ACTIONS DESC;


-- 6. Risk-class calibration: how often does TRUE_RUL fall within the class window?
WITH joined AS (
    SELECT
        fp.RISK_CLASS,
        fp.RUL_PREDICTION,
        gt.TRUE_RUL
    FROM FLEET_PREDICTIONS fp
    JOIN FLEET_GROUND_TRUTH gt
      ON gt.MACHINE_ID = fp.MACHINE_ID
    JOIN MACHINE_DATA m
      ON m.MACHINE_ID = fp.MACHINE_ID
    WHERE m.STATUS = 'IN_SERVICE'
)
SELECT
    RISK_CLASS,
    COUNT(*)                              AS ENGINES,
    ROUND(AVG(RUL_PREDICTION), 1)         AS AVG_PREDICTED_RUL,
    ROUND(AVG(TRUE_RUL), 1)              AS AVG_TRUE_RUL,
    ROUND(
        SUM(CASE
            WHEN RISK_CLASS = 'CRITICAL' AND TRUE_RUL <= 15  THEN 1
            WHEN RISK_CLASS = 'HIGH'     AND TRUE_RUL <= 40  THEN 1
            WHEN RISK_CLASS = 'MEDIUM'   AND TRUE_RUL <= 90  THEN 1
            ELSE 0
        END)::FLOAT
        / NULLIF(
            SUM(CASE WHEN RISK_CLASS IN ('CRITICAL','HIGH','MEDIUM') THEN 1 ELSE 0 END),
            0),
        3)                                AS FAIL_IN_WINDOW_RATE
FROM joined
GROUP BY RISK_CLASS
ORDER BY
    CASE RISK_CLASS
        WHEN 'CRITICAL' THEN 1
        WHEN 'HIGH'     THEN 2
        WHEN 'MEDIUM'   THEN 3
        WHEN 'LOW'      THEN 4
    END;
