-- Live replay: hold back each in-service engine's last real cycles, then stream them back

USE SCHEMA PDM.PUBLIC;

CREATE TABLE IF NOT EXISTS REPLAY_QUEUE LIKE RAW_SENSOR_DATA;
ALTER TABLE REPLAY_QUEUE ADD COLUMN IF NOT EXISTS REPLAY_STEP NUMBER;

CREATE OR REPLACE PROCEDURE REPLAY_PREPARE(HOLD_BACK_CYCLES INTEGER)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    queued INTEGER;
BEGIN
    SELECT COUNT(*) INTO :queued FROM REPLAY_QUEUE;
    IF (queued > 0) THEN
        RETURN 'A replay is already in progress (' || queued || ' readings queued). Run REPLAY_RESTORE() first.';
    END IF;

    INSERT INTO REPLAY_QUEUE (MACHINE_ID, TIME_CYCLE, OP_SETTING_1, OP_SETTING_2, OP_SETTING_3, SENSOR_1, SENSOR_2, SENSOR_3, SENSOR_4, SENSOR_5, SENSOR_6, SENSOR_7, SENSOR_8, SENSOR_9, SENSOR_10, SENSOR_11, SENSOR_12, SENSOR_13, SENSOR_14, SENSOR_15, SENSOR_16, SENSOR_17, SENSOR_18, SENSOR_19, SENSOR_20, SENSOR_21, REPLAY_STEP)
    SELECT MACHINE_ID, TIME_CYCLE, OP_SETTING_1, OP_SETTING_2, OP_SETTING_3, SENSOR_1, SENSOR_2, SENSOR_3, SENSOR_4, SENSOR_5, SENSOR_6, SENSOR_7, SENSOR_8, SENSOR_9, SENSOR_10, SENSOR_11, SENSOR_12, SENSOR_13, SENSOR_14, SENSOR_15, SENSOR_16, SENSOR_17, SENSOR_18, SENSOR_19, SENSOR_20, SENSOR_21,
           ROW_NUMBER() OVER (PARTITION BY MACHINE_ID ORDER BY TIME_CYCLE) AS REPLAY_STEP
    FROM (
        SELECT r.*,
               ROW_NUMBER() OVER (PARTITION BY r.MACHINE_ID ORDER BY r.TIME_CYCLE DESC) AS FROM_END,
               COUNT(*) OVER (PARTITION BY r.MACHINE_ID) AS N_CYCLES
        FROM RAW_SENSOR_DATA r
        JOIN MACHINE_DATA m ON m.MACHINE_ID = r.MACHINE_ID AND m.STATUS = 'IN_SERVICE'
    )
    WHERE FROM_END <= LEAST(:HOLD_BACK_CYCLES, N_CYCLES - 15);
    queued := SQLROWCOUNT;

    DELETE FROM RAW_SENSOR_DATA r USING REPLAY_QUEUE q
    WHERE r.MACHINE_ID = q.MACHINE_ID AND r.TIME_CYCLE = q.TIME_CYCLE;

    CALL SCORE_FLEET();
    RETURN 'Fleet rewound: ' || queued || ' real readings held back and the fleet rescored. Stream them with REPLAY_STEP(1).';
END;
$$;

CREATE OR REPLACE PROCEDURE REPLAY_STEP(CYCLES INTEGER)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    next_step INTEGER;
    streamed INTEGER;
    remaining INTEGER;
BEGIN
    SELECT MIN(REPLAY_STEP) INTO :next_step FROM REPLAY_QUEUE;
    IF (next_step IS NULL) THEN
        RETURN 'Nothing to stream: the fleet is at its latest NASA readings.';
    END IF;

    INSERT INTO RAW_SENSOR_DATA (MACHINE_ID, TIME_CYCLE, OP_SETTING_1, OP_SETTING_2, OP_SETTING_3, SENSOR_1, SENSOR_2, SENSOR_3, SENSOR_4, SENSOR_5, SENSOR_6, SENSOR_7, SENSOR_8, SENSOR_9, SENSOR_10, SENSOR_11, SENSOR_12, SENSOR_13, SENSOR_14, SENSOR_15, SENSOR_16, SENSOR_17, SENSOR_18, SENSOR_19, SENSOR_20, SENSOR_21)
    SELECT MACHINE_ID, TIME_CYCLE, OP_SETTING_1, OP_SETTING_2, OP_SETTING_3, SENSOR_1, SENSOR_2, SENSOR_3, SENSOR_4, SENSOR_5, SENSOR_6, SENSOR_7, SENSOR_8, SENSOR_9, SENSOR_10, SENSOR_11, SENSOR_12, SENSOR_13, SENSOR_14, SENSOR_15, SENSOR_16, SENSOR_17, SENSOR_18, SENSOR_19, SENSOR_20, SENSOR_21 FROM REPLAY_QUEUE WHERE REPLAY_STEP < :next_step + :CYCLES;
    streamed := SQLROWCOUNT;
    DELETE FROM REPLAY_QUEUE WHERE REPLAY_STEP < :next_step + :CYCLES;
    SELECT COUNT(*) INTO :remaining FROM REPLAY_QUEUE;

    RETURN streamed || ' real readings streamed; ' || remaining || ' still queued. '
        || 'SCORE_FLEET_TASK rescores the fleet within about a minute.';
END;
$$;

CREATE OR REPLACE PROCEDURE REPLAY_RESTORE()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    restored INTEGER;
BEGIN
    INSERT INTO RAW_SENSOR_DATA (MACHINE_ID, TIME_CYCLE, OP_SETTING_1, OP_SETTING_2, OP_SETTING_3, SENSOR_1, SENSOR_2, SENSOR_3, SENSOR_4, SENSOR_5, SENSOR_6, SENSOR_7, SENSOR_8, SENSOR_9, SENSOR_10, SENSOR_11, SENSOR_12, SENSOR_13, SENSOR_14, SENSOR_15, SENSOR_16, SENSOR_17, SENSOR_18, SENSOR_19, SENSOR_20, SENSOR_21)
    SELECT MACHINE_ID, TIME_CYCLE, OP_SETTING_1, OP_SETTING_2, OP_SETTING_3, SENSOR_1, SENSOR_2, SENSOR_3, SENSOR_4, SENSOR_5, SENSOR_6, SENSOR_7, SENSOR_8, SENSOR_9, SENSOR_10, SENSOR_11, SENSOR_12, SENSOR_13, SENSOR_14, SENSOR_15, SENSOR_16, SENSOR_17, SENSOR_18, SENSOR_19, SENSOR_20, SENSOR_21 FROM REPLAY_QUEUE;
    restored := SQLROWCOUNT;
    DELETE FROM REPLAY_QUEUE;
    RETURN restored || ' readings restored; the fleet is at its latest NASA readings.';
END;
$$;
